version: '3.9'

services:
  db:
    build: .
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

