# Usar la imagen base oficial de PostgreSQL
FROM postgres:16

# Establecer variables de entorno para la configuración de PostgreSQL
ENV POSTGRES_PASSWORD=juan-1234

# Exponer el puerto PostgreSQL
EXPOSE 5432

